name: CI

on: #Merges when pull request to Master branch is created
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    #Copied from Marketplace in GitHub
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

  test:
    needs: [build] #Can only start when build is finished needs build to be finished
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B clean test #Using Maven this runs the clean phase(removes target file) and test phase in Maven lifecycle