name: CI

on: #Merges when pull request to Master branch is created
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    #Copied from Marketplace in Github
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'